services:
  # Backend API сервис
  backend:
    build: .
    container_name: yandex-search-backend
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      - GUNICORN_WORKERS=4
      - GUNICORN_TIMEOUT=120
    volumes:
      # Монтируем .env файл для переменных окружения
      - ./.env:/app/.env:ro
      # Монтируем директорию для экспорта Excel файлов
      - ./exports:/app/exports
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/get_status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - yandex-network

  # Frontend сервис
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: yandex-search-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - yandex-network

networks:
  yandex-network:
    driver: bridge
