services:
  yandex-search-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    volumes:
      # Монтируем .env файл для переменных окружения
      - ./.env:/app/.env:ro
      # Монтируем директорию для экспорта Excel файлов
      - ./exports:/app/exports
      # Hot reload для development
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/get_status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Опциональный nginx для статических файлов
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - yandex-search-app-dev
    restart: unless-stopped
